---
abstract: 'add a websocket interface to your Dancers app'
author:
  - 'Yanick Champoux <yanick@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Test::More: '0'
  Test::Requires: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.017, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dancer2-Plugin-WebSocket
provides:
  Dancer2::Plugin::WebSocket:
    file: lib/Dancer2/Plugin/WebSocket.pm
    version: v0.3.0
  Dancer2::Plugin::WebSocket::Connection:
    file: lib/Dancer2/Plugin/WebSocket/Connection.pm
    version: v0.3.0
  Dancer2::Plugin::WebSocket::Group:
    file: lib/Dancer2/Plugin/WebSocket/Group.pm
    version: v0.3.0
requires:
  Dancer2::Plugin: '0'
  JSON::MaybeXS: '0'
  Moo: '0'
  Moo::Role: '0'
  Plack::App::WebSocket: '0'
  Scalar::Util: '0'
  Set::Tiny: '0'
  Try::Tiny: '0'
  perl: v5.12.0
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/yanick/Dancer2-Plugin-WebSocket/issues
  homepage: https://github.com/yanick/Dancer2-Plugin-WebSocket
  repository: https://github.com/yanick/Dancer2-Plugin-WebSocket.git
version: 0.3.0
x_author_pledge:
  version: 1
x_authority: cpan:YANICK
x_contributor_covenant:
  version: 0.02
x_contributors:
  - 'Frank Schreiner <schreiner@suse.de>'
  - 'Mohammad S Anwar <mohammad.anwar@yahoo.com>'
  - 'Vladislav Kantor <kantor.vladisla@gmail.com>'
  - 'Yanick Champoux <yanick@babyl.ca>'
x_generated_by_perl: v5.30.0
x_serialization_backend: 'YAML::Tiny version 1.73'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
